export const CLOTHING_SUBDIVISIONS = {
  tops: [
    'T-shirt',
    'Tank top',
    'Blouse',
    'Shirt',
    'Polo shirt',
    'Sweater',
    'Cardigan',
    'Hoodie',
    'Sweatshirt',
    'Crop top',
    'Tube top',
    'Halter top',
    'Off-shoulder top',
    'Long sleeve shirt',
    'Button-up shirt',
    'Flannel shirt',
    'Henley shirt',
    'Turtleneck',
    'V-neck top',
    'Scoop neck top'
  ],
  bottoms: [
    'Jeans',
    'Pants',
    'Shorts',
    'Skirt',
    'Dress pants',
    'Chinos',
    'Leggings',
    'Joggers',
    'Sweatpants',
    'Cargo pants',
    'Wide-leg pants',
    'Skinny jeans',
    'Straight jeans',
    'Bootcut jeans',
    'High-waisted pants',
    'Capri pants',
    'Bermuda shorts',
    'Mini skirt',
    'Midi skirt',
    'Maxi skirt'
  ],
  shoes: [
    'Sneakers',
    'Boots',
    'Sandals',
    'Heels',
    'Flats',
    'Loafers',
    'Oxford shoes',
    'Running shoes',
    'Basketball shoes',
    'Hiking boots',
    'Ankle boots',
    'Knee-high boots',
    'Flip-flops',
    'Wedges',
    'Platform shoes',
    'Slip-on shoes',
    'Canvas shoes',
    'Dress shoes',
    'Clogs',
    'Espadrilles'
  ],
  accessories: [
    'Hat',
    'Cap',
    'Scarf',
    'Belt',
    'Watch',
    'Sunglasses',
    'Jewelry',
    'Bag',
    'Backpack',
    'Purse',
    'Wallet',
    'Gloves',
    'Tie',
    'Bow tie',
    'Hair accessories',
    'Earrings',
    'Necklace',
    'Bracelet',
    'Ring',
    'Brooch'
  ],
  outerwear: [
    'Jacket',
    'Coat',
    'Blazer',
    'Windbreaker',
    'Raincoat',
    'Puffer jacket',
    'Leather jacket',
    'Denim jacket',
    'Bomber jacket',
    'Trench coat',
    'Peacoat',
    'Parka',
    'Vest',
    'Cardigan coat',
    'Cape',
    'Poncho',
    'Shawl',
    'Wrap',
    'Kimono',
    'Robe'
  ]
};

export const CLOTHING_STYLES = [
  'casual',
  'formal',
  'sporty',
  'elegant',
  'vintage',
  'trendy',
  'bohemian',
  'minimalist',
  'edgy',
  'romantic',
  'preppy',
  'streetwear',
  'business',
  'party',
  'beach',
  'athletic'
];

export const CLOTHING_SEASONS = [
  'spring',
  'summer',
  'fall',
  'winter',
  'all-season'
];

export const CLOTHING_COLORS = [
  'black',
  'white',
  'gray',
  'red',
  'blue',
  'green',
  'yellow',
  'orange',
  'purple',
  'pink',
  'brown',
  'beige',
  'navy',
  'maroon',
  'teal',
  'coral',
  'turquoise',
  'lavender',
  'mint',
  'cream',
  'khaki',
  'burgundy',
  'olive',
  'gold',
  'silver'
];